default: &default
  url: 'redis://localhost:6379/0'
  pool_size: 50
  timeout: 10

development:
  <<: *default
test:
  url: 'redis://localhost:6379/1'
  <<: *default

production:
  url: <%= ENV['REDIS_URL'] %>
  pool_size: <%= ENV['REDIS_POOL_SIZE'] %>
  timeout: <%= ENV['REDIS_TIMEOUT'] %>
